# Generated by Django 3.0.6 on 2020-06-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_druzyny', models.CharField(max_length=200)),
                ('adres_klubu', models.CharField(max_length=200)),
                ('aktualna_liga', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Miejscowosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_miejscowosci', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pilkarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('data_urodzenia', models.DateTimeField(blank=True, null=True)),
                ('id_druzyna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Druzyna')),
            ],
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozegrania', models.DateTimeField(blank=True, null=True)),
                ('wynik_goscia', models.IntegerField(default=0)),
                ('wynik_gospodarza', models.IntegerField(default=0)),
                ('druzyna_gosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druzyna_gosci', to='blog.Druzyna')),
                ('druzyna_gospodarzy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druzyna_gospodarzy', to='blog.Druzyna')),
                ('id_miejscowosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Miejscowosc')),
            ],
        ),
        migrations.CreateModel(
            name='Granie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.CharField(max_length=200)),
                ('liczba_strzelonych_bramek', models.IntegerField(default=0)),
                ('minuta_czerwnoej_kartki', models.IntegerField(default=0)),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Mecz')),
                ('id_pilkarza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pilkarz')),
            ],
        ),
        migrations.AddField(
            model_name='druzyna',
            name='id_miejscowosc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Miejscowosc'),
        ),
    ]
