# Generated by Django 3.0.6 on 2020-06-03 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200603_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='granie',
            name='statystki_mecz',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mecz',
            name='nazwa_meczu',
            field=models.CharField(default=datetime.datetime(2020, 6, 3, 11, 10, 9, 354621, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mecz',
            name='druzyna_gosci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druzyna_goscii', to='blog.Druzyna'),
        ),
        migrations.AlterField(
            model_name='mecz',
            name='druzyna_gospodarzy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druzyna_gospodarzyy', to='blog.Druzyna'),
        ),
    ]
